//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IMSMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IMSMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IMS.Common.Core.IMSMessages", typeof(IMSMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///you received this email following the creation of an account on Trendigo.com web site. In order to proceed with your account, you are invited to click on the link below so we can  validate your email address. Once the authentication is done, you will be able to complete your Trendigo account.
        ///
        ///{0}
        ///
        ///This is an automated message, it is unnecessary to reply to this email. However, if you wish to contact Trendigo, you can reach us by email at info@trendigo.com or on our toll free number  at 1-844- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CourrielValidationBody_en {
            get {
                return ResourceManager.GetString("CourrielValidationBody_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonjour,
        /// 
        ///vous recevez ce courriel suite à la création d’un profil sur le site Trendigo.com. Pour poursuivre la création de votre compte, vous devez cliquer sur le lien ci-dessous afin de valider l’authenticité de votre adresse courriel. Une fois votre courriel authentifié, vous serez en mesure de compléter votre compte Trendigo.
        /// 
        ///{0}
        /// 
        ///Ce courriel est un envoi automatisé, il est inutile de répondre à ce courriel. Si toutefois vous désirez contacter Trendigo, nous vous suggérons d’utiliser l’adresse [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CourrielValidationBody_fr {
            get {
                return ResourceManager.GetString("CourrielValidationBody_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your account.
        /// </summary>
        public static string CourrielValidationSubject_en {
            get {
                return ResourceManager.GetString("CourrielValidationSubject_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation du compte.
        /// </summary>
        public static string CourrielValidationSubject_fr {
            get {
                return ResourceManager.GetString("CourrielValidationSubject_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shared with you a Trendigo local hot-spot!.
        /// </summary>
        public static string SharePromoEmailSubject_en {
            get {
                return ResourceManager.GetString("SharePromoEmailSubject_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vous a partagé une bonne adresse sur Trendigo!.
        /// </summary>
        public static string SharePromoEmailSubject_fr {
            get {
                return ResourceManager.GetString("SharePromoEmailSubject_fr", resourceCulture);
            }
        }
    }
}
