//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Service.WebAPI2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IMS.Service.WebAPI2.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account creation failed.
        /// </summary>
        internal static string AccountCreationFailed_en {
            get {
                return ResourceManager.GetString("AccountCreationFailed_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La création du compte a échoué.
        /// </summary>
        internal static string AccountCreationFailed_fr {
            get {
                return ResourceManager.GetString("AccountCreationFailed_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account locked.
        /// </summary>
        internal static string AccountLocked_en {
            get {
                return ResourceManager.GetString("AccountLocked_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compte bloqué.
        /// </summary>
        internal static string AccountLocked_fr {
            get {
                return ResourceManager.GetString("AccountLocked_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banking information already exist.
        /// </summary>
        internal static string BankingInfoExist_en {
            get {
                return ResourceManager.GetString("BankingInfoExist_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les informations bancaires exitent déjà.
        /// </summary>
        internal static string BankingInfoExist_fr {
            get {
                return ResourceManager.GetString("BankingInfoExist_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banking info not found.
        /// </summary>
        internal static string BankingInfoNotFound_en {
            get {
                return ResourceManager.GetString("BankingInfoNotFound_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information bancaire introuvable.
        /// </summary>
        internal static string BankingInfoNotFound_fr {
            get {
                return ResourceManager.GetString("BankingInfoNotFound_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business hour was successfully deleted.
        /// </summary>
        internal static string BusinessHourDeleted_en {
            get {
                return ResourceManager.GetString("BusinessHourDeleted_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les heures d&apos;ouverture ont été supprimées avec succès.
        /// </summary>
        internal static string BusinessHourDeleted_fr {
            get {
                return ResourceManager.GetString("BusinessHourDeleted_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business hour exist for that day.
        /// </summary>
        internal static string BusinessHourExistForThatDay_en {
            get {
                return ResourceManager.GetString("BusinessHourExistForThatDay_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les heures d&apos;ouvertures existent pour ce jour.
        /// </summary>
        internal static string BusinessHourExistForThatDay_fr {
            get {
                return ResourceManager.GetString("BusinessHourExistForThatDay_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business hour not found.
        /// </summary>
        internal static string BusinessHourNotFound_en {
            get {
                return ResourceManager.GetString("BusinessHourNotFound_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heures d&apos;ouverture introuvable.
        /// </summary>
        internal static string BusinessHourNotFound_fr {
            get {
                return ResourceManager.GetString("BusinessHourNotFound_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add new image.
        /// </summary>
        internal static string CannotAddNewImage_en {
            get {
                return ResourceManager.GetString("CannotAddNewImage_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter une nouvelle image.
        /// </summary>
        internal static string CannotAddNewImage_fr {
            get {
                return ResourceManager.GetString("CannotAddNewImage_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add new image, quota has been reached.
        /// </summary>
        internal static string CannotAddNewImageQuotaReached_en {
            get {
                return ResourceManager.GetString("CannotAddNewImageQuotaReached_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter une nouvelle image, le quota a été atteint.
        /// </summary>
        internal static string CannotAddNewImageQuotaReached_fr {
            get {
                return ResourceManager.GetString("CannotAddNewImageQuotaReached_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change password for that member.
        /// </summary>
        internal static string CannotChangePasswordForThatMember_en {
            get {
                return ResourceManager.GetString("CannotChangePasswordForThatMember_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de changer le mot de passe pour ce membre.
        /// </summary>
        internal static string CannotChangePasswordForThatMember_fr {
            get {
                return ResourceManager.GetString("CannotChangePasswordForThatMember_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create member.
        /// </summary>
        internal static string CannotCreateMember_en {
            get {
                return ResourceManager.GetString("CannotCreateMember_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de créer le membre.
        /// </summary>
        internal static string CannotCreateMember_fr {
            get {
                return ResourceManager.GetString("CannotCreateMember_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create user.
        /// </summary>
        internal static string CannotCreateUser_en {
            get {
                return ResourceManager.GetString("CannotCreateUser_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de créer l&apos;utilisateur.
        /// </summary>
        internal static string CannotCreateUser_fr {
            get {
                return ResourceManager.GetString("CannotCreateUser_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community added successfully.
        /// </summary>
        internal static string CommunityAddedSuccessfully_en {
            get {
                return ResourceManager.GetString("CommunityAddedSuccessfully_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La communauté a été ajouté avec succès.
        /// </summary>
        internal static string CommunityAddedSuccessfully_fr {
            get {
                return ResourceManager.GetString("CommunityAddedSuccessfully_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community already exist.
        /// </summary>
        internal static string CommunityAlreadyExist_en {
            get {
                return ResourceManager.GetString("CommunityAlreadyExist_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce nom de communauté est déjà existant.
        /// </summary>
        internal static string CommunityAlreadyExist_fr {
            get {
                return ResourceManager.GetString("CommunityAlreadyExist_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community join successfully.
        /// </summary>
        internal static string CommunityJoinSuccessfully_en {
            get {
                return ResourceManager.GetString("CommunityJoinSuccessfully_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communauté jointe avec succès.
        /// </summary>
        internal static string CommunityJoinSuccessfully_fr {
            get {
                return ResourceManager.GetString("CommunityJoinSuccessfully_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community not found.
        /// </summary>
        internal static string CommunityNotFound_en {
            get {
                return ResourceManager.GetString("CommunityNotFound_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communauté introuvable.
        /// </summary>
        internal static string CommunityNotFound_fr {
            get {
                return ResourceManager.GetString("CommunityNotFound_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email validation.
        /// </summary>
        internal static string CourrielEmailValidationSubject_en {
            get {
                return ResourceManager.GetString("CourrielEmailValidationSubject_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation du courriel.
        /// </summary>
        internal static string CourrielEmailValidationSubject_fr {
            get {
                return ResourceManager.GetString("CourrielEmailValidationSubject_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm my email.
        /// </summary>
        internal static string CourrielEmailValidationTextLink_en {
            get {
                return ResourceManager.GetString("CourrielEmailValidationTextLink_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer mon adresse courriel.
        /// </summary>
        internal static string CourrielEmailValidationTextLink_fr {
            get {
                return ResourceManager.GetString("CourrielEmailValidationTextLink_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your password by clicking here: {0}.
        /// </summary>
        internal static string CourrielPasswordResetBody_en {
            get {
                return ResourceManager.GetString("CourrielPasswordResetBody_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez réinitialiser votre mot de passe en cliquant ici: {0}.
        /// </summary>
        internal static string CourrielPasswordResetBody_fr {
            get {
                return ResourceManager.GetString("CourrielPasswordResetBody_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset.
        /// </summary>
        internal static string CourrielPasswordResetSubject_en {
            get {
                return ResourceManager.GetString("CourrielPasswordResetSubject_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialisation du mot de passe.
        /// </summary>
        internal static string CourrielPasswordResetSubject_fr {
            get {
                return ResourceManager.GetString("CourrielPasswordResetSubject_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset my password.
        /// </summary>
        internal static string CourrielPasswordResetTextLink_en {
            get {
                return ResourceManager.GetString("CourrielPasswordResetTextLink_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser mon mot de passe.
        /// </summary>
        internal static string CourrielPasswordResetTextLink_fr {
            get {
                return ResourceManager.GetString("CourrielPasswordResetTextLink_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You completed your registration!.
        /// </summary>
        internal static string CourrielProfileCompletionSubject_en {
            get {
                return ResourceManager.GetString("CourrielProfileCompletionSubject_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez complété votre inscription!.
        /// </summary>
        internal static string CourrielProfileCompletionSubject_fr {
            get {
                return ResourceManager.GetString("CourrielProfileCompletionSubject_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration confirmation!.
        /// </summary>
        internal static string CourrielRegisterMemberSubject_en {
            get {
                return ResourceManager.GetString("CourrielRegisterMemberSubject_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation d’inscription Trendigo!.
        /// </summary>
        internal static string CourrielRegisterMemberSubject_fr {
            get {
                return ResourceManager.GetString("CourrielRegisterMemberSubject_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        internal static string CourrielSetPasswordSubject_en {
            get {
                return ResourceManager.GetString("CourrielSetPasswordSubject_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertion du mot de passe.
        /// </summary>
        internal static string CourrielSetPasswordSubject_fr {
            get {
                return ResourceManager.GetString("CourrielSetPasswordSubject_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set my password.
        /// </summary>
        internal static string CourrielSetPasswordTextLink_en {
            get {
                return ResourceManager.GetString("CourrielSetPasswordTextLink_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insérer mon mot de passe.
        /// </summary>
        internal static string CourrielSetPasswordTextLink_fr {
            get {
                return ResourceManager.GetString("CourrielSetPasswordTextLink_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card already exist.
        /// </summary>
        internal static string CreditCardAlreadyExist_en {
            get {
                return ResourceManager.GetString("CreditCardAlreadyExist_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La carte de crédit existe déjà.
        /// </summary>
        internal static string CreditCardAlreadyExist_fr {
            get {
                return ResourceManager.GetString("CreditCardAlreadyExist_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card was successfully deleted.
        /// </summary>
        internal static string CreditCardDeleted_en {
            get {
                return ResourceManager.GetString("CreditCardDeleted_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La carte de crédit a été supprimée avec succès.
        /// </summary>
        internal static string CreditCardDeleted_fr {
            get {
                return ResourceManager.GetString("CreditCardDeleted_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card not found.
        /// </summary>
        internal static string CreditCardNotFound_en {
            get {
                return ResourceManager.GetString("CreditCardNotFound_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carte de crédit introuvable.
        /// </summary>
        internal static string CreditCardNotFound_fr {
            get {
                return ResourceManager.GetString("CreditCardNotFound_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card updated successfully.
        /// </summary>
        internal static string CreditCardUpdated_en {
            get {
                return ResourceManager.GetString("CreditCardUpdated_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carte de crédit mise à jour avec succès.
        /// </summary>
        internal static string CreditCardUpdated_fr {
            get {
                return ResourceManager.GetString("CreditCardUpdated_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address was validated successfully.
        /// </summary>
        internal static string EmailAddressValidated_en {
            get {
                return ResourceManager.GetString("EmailAddressValidated_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse courriel validé avec succès.
        /// </summary>
        internal static string EmailAddressValidated_fr {
            get {
                return ResourceManager.GetString("EmailAddressValidated_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already used.
        /// </summary>
        internal static string EmailAlreadyUsed_en {
            get {
                return ResourceManager.GetString("EmailAlreadyUsed_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse courriel déjà utilisée.
        /// </summary>
        internal static string EmailAlreadyUsed_fr {
            get {
                return ResourceManager.GetString("EmailAlreadyUsed_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not validated.
        /// </summary>
        internal static string EmailNotValidated_en {
            get {
                return ResourceManager.GetString("EmailNotValidated_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel non confirmé.
        /// </summary>
        internal static string EmailNotValidated_fr {
            get {
                return ResourceManager.GetString("EmailNotValidated_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email validation necessary before performing this action, please check your inbox of the account used for this application and proceed with the confirmation.
        /// </summary>
        internal static string EmailValidationNecessary_en {
            get {
                return ResourceManager.GetString("EmailValidationNecessary_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation de l&apos;adresse courriel nécessaire avant d&apos;effectuer cette action, veuillez vérifier votre boîte de réception du compte utilisé pour cette application et procéder avec la confirmation.
        /// </summary>
        internal static string EmailValidationNecessary_fr {
            get {
                return ResourceManager.GetString("EmailValidationNecessary_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending date is not a valid date.
        /// </summary>
        internal static string EndingDateNotAValidDate_en {
            get {
                return ResourceManager.GetString("EndingDateNotAValidDate_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de fin n&apos;est pas valide.
        /// </summary>
        internal static string EndingDateNotAValidDate_fr {
            get {
                return ResourceManager.GetString("EndingDateNotAValidDate_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday already exist for that date.
        /// </summary>
        internal static string HolidayAlreadyExist_en {
            get {
                return ResourceManager.GetString("HolidayAlreadyExist_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un congé existe déjà pour cette date.
        /// </summary>
        internal static string HolidayAlreadyExist_fr {
            get {
                return ResourceManager.GetString("HolidayAlreadyExist_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday deleted successfully.
        /// </summary>
        internal static string HolidayDeleted_en {
            get {
                return ResourceManager.GetString("HolidayDeleted_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le congé a été supprimé avec succès.
        /// </summary>
        internal static string HolidayDeleted_fr {
            get {
                return ResourceManager.GetString("HolidayDeleted_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image deleted successfully.
        /// </summary>
        internal static string ImageDeleted_en {
            get {
                return ResourceManager.GetString("ImageDeleted_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image suppriméé avec succès.
        /// </summary>
        internal static string ImageDeleted_fr {
            get {
                return ResourceManager.GetString("ImageDeleted_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image not found.
        /// </summary>
        internal static string ImageNotFound_en {
            get {
                return ResourceManager.GetString("ImageNotFound_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image introuvable.
        /// </summary>
        internal static string ImageNotFound_fr {
            get {
                return ResourceManager.GetString("ImageNotFound_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size must be less than 2mb.
        /// </summary>
        internal static string ImageSizeNotAccepted_en {
            get {
                return ResourceManager.GetString("ImageSizeNotAccepted_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La taille de l&apos;image ne doit pas dépasser 2mb.
        /// </summary>
        internal static string ImageSizeNotAccepted_fr {
            get {
                return ResourceManager.GetString("ImageSizeNotAccepted_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image type must be .jpg, .gif or .png.
        /// </summary>
        internal static string ImageTypeNotAccepted_en {
            get {
                return ResourceManager.GetString("ImageTypeNotAccepted_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type d&apos;image doit être .jpg, .gif ou .png.
        /// </summary>
        internal static string ImageTypeNotAccepted_fr {
            get {
                return ResourceManager.GetString("ImageTypeNotAccepted_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image type not found.
        /// </summary>
        internal static string ImageTypeNotFound_en {
            get {
                return ResourceManager.GetString("ImageTypeNotFound_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type d&apos;image introuvable.
        /// </summary>
        internal static string ImageTypeNotFound_fr {
            get {
                return ResourceManager.GetString("ImageTypeNotFound_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string InvalidUsernameOrPassword_en {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code d&apos;utilisateur ou mot de passe invalide.
        /// </summary>
        internal static string InvalidUsernameOrPassword_fr {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice not found.
        /// </summary>
        internal static string InvoiceNotFound_en {
            get {
                return ResourceManager.GetString("InvoiceNotFound_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La facture est introuvable.
        /// </summary>
        internal static string InvoiceNotFound_fr {
            get {
                return ResourceManager.GetString("InvoiceNotFound_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language not found.
        /// </summary>
        internal static string LanguageNotFound_en {
            get {
                return ResourceManager.GetString("LanguageNotFound_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue introuvable.
        /// </summary>
        internal static string LanguageNotFound_fr {
            get {
                return ResourceManager.GetString("LanguageNotFound_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link was sent successfully.
        /// </summary>
        internal static string LinkWasSentSuccessfully_en {
            get {
                return ResourceManager.GetString("LinkWasSentSuccessfully_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le lien a été envoyé avec succès.
        /// </summary>
        internal static string LinkWasSentSuccessfully_fr {
            get {
                return ResourceManager.GetString("LinkWasSentSuccessfully_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member was successfully deleted.
        /// </summary>
        internal static string MemberDeleted_en {
            get {
                return ResourceManager.GetString("MemberDeleted_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le membre a été supprimé avec succès.
        /// </summary>
        internal static string MemberDeleted_fr {
            get {
                return ResourceManager.GetString("MemberDeleted_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member not found.
        /// </summary>
        internal static string MemberNotFound_en {
            get {
                return ResourceManager.GetString("MemberNotFound_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membre introuvable.
        /// </summary>
        internal static string MemberNotFound_fr {
            get {
                return ResourceManager.GetString("MemberNotFound_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant already part of a community.
        /// </summary>
        internal static string MerchantAlreadyInCommunity_en {
            get {
                return ResourceManager.GetString("MerchantAlreadyInCommunity_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le marchand fait déjà partie d&apos;une communauté.
        /// </summary>
        internal static string MerchantAlreadyInCommunity_fr {
            get {
                return ResourceManager.GetString("MerchantAlreadyInCommunity_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant was successfully deleted.
        /// </summary>
        internal static string MerchantDeleted_en {
            get {
                return ResourceManager.GetString("MerchantDeleted_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le marchand a été supprimé avec succès.
        /// </summary>
        internal static string MerchantDeleted_fr {
            get {
                return ResourceManager.GetString("MerchantDeleted_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant not found.
        /// </summary>
        internal static string MerchantNotFound_en {
            get {
                return ResourceManager.GetString("MerchantNotFound_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marchand introuvable.
        /// </summary>
        internal static string MerchantNotFound_fr {
            get {
                return ResourceManager.GetString("MerchantNotFound_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The merchant is not open on that date.
        /// </summary>
        internal static string MerchantNotOpenOnThatDate_en {
            get {
                return ResourceManager.GetString("MerchantNotOpenOnThatDate_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le marchand n&apos;est pas ouvert à cette date.
        /// </summary>
        internal static string MerchantNotOpenOnThatDate_fr {
            get {
                return ResourceManager.GetString("MerchantNotOpenOnThatDate_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag not found for that merchant.
        /// </summary>
        internal static string MerchantTagNotFound_en {
            get {
                return ResourceManager.GetString("MerchantTagNotFound_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag introuvable pour ce marchand.
        /// </summary>
        internal static string MerchantTagNotFounf_fr {
            get {
                return ResourceManager.GetString("MerchantTagNotFounf_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant tag removed successfully.
        /// </summary>
        internal static string MerchantTagRemoved_en {
            get {
                return ResourceManager.GetString("MerchantTagRemoved_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag retiré de ce marchand avec succès.
        /// </summary>
        internal static string MerchantTagRemoved_fr {
            get {
                return ResourceManager.GetString("MerchantTagRemoved_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing parameter.
        /// </summary>
        internal static string MissingParameter_en {
            get {
                return ResourceManager.GetString("MissingParameter_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètre manquant.
        /// </summary>
        internal static string MissingParameter_fr {
            get {
                return ResourceManager.GetString("MissingParameter_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No localisation found for that geolocation.
        /// </summary>
        internal static string NoLocalisationFound_en {
            get {
                return ResourceManager.GetString("NoLocalisationFound_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune localisation trouvée pour cette géolocalisation.
        /// </summary>
        internal static string NoLocalisationFound_fr {
            get {
                return ResourceManager.GetString("NoLocalisationFound_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card not yet activated.
        /// </summary>
        internal static string NotActivated_en {
            get {
                return ResourceManager.GetString("NotActivated_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carte non-activée.
        /// </summary>
        internal static string NotActivated_fr {
            get {
                return ResourceManager.GetString("NotActivated_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification added successfully.
        /// </summary>
        internal static string NotificationAddedSuccessfully_en {
            get {
                return ResourceManager.GetString("NotificationAddedSuccessfully_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification ajoutée avec succès.
        /// </summary>
        internal static string NotificationAddedSuccessfully_fr {
            get {
                return ResourceManager.GetString("NotificationAddedSuccessfully_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date unavailable, this is not an open business day for that merchant.
        /// </summary>
        internal static string NotOpenBusinessDay_en {
            get {
                return ResourceManager.GetString("NotOpenBusinessDay_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date non disponible, ce n&apos;est pas un jour ouvrable pour ce marchand.
        /// </summary>
        internal static string NotOpenBusinessDay_fr {
            get {
                return ResourceManager.GetString("NotOpenBusinessDay_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date unavailable, this is a holiday period for that merchant.
        /// </summary>
        internal static string NotOpenHoliday_en {
            get {
                return ResourceManager.GetString("NotOpenHoliday_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date non disponible, il s&apos;agit d&apos;une période de congé pour ce marchand.
        /// </summary>
        internal static string NotOpenHoliday_fr {
            get {
                return ResourceManager.GetString("NotOpenHoliday_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully updated.
        /// </summary>
        internal static string PasswordSuccessfullyUpdated_en {
            get {
                return ResourceManager.GetString("PasswordSuccessfullyUpdated_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe mis à jour avec succès.
        /// </summary>
        internal static string PasswordSuccessfullyUpdated_fr {
            get {
                return ResourceManager.GetString("PasswordSuccessfullyUpdated_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password was set successfully.
        /// </summary>
        internal static string PasswordWasSetSuccessfully_en {
            get {
                return ResourceManager.GetString("PasswordWasSetSuccessfully_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe défini avec succès.
        /// </summary>
        internal static string PasswordWasSetSuccessfully_fr {
            get {
                return ResourceManager.GetString("PasswordWasSetSuccessfully_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo code not found.
        /// </summary>
        internal static string PromoCodeNotFound_en {
            get {
                return ResourceManager.GetString("PromoCodeNotFound_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code promotionnel introuvable.
        /// </summary>
        internal static string PromoCodeNotFound_fr {
            get {
                return ResourceManager.GetString("PromoCodeNotFound_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating added successfully.
        /// </summary>
        internal static string RatingAddedSuccessfully_en {
            get {
                return ResourceManager.GetString("RatingAddedSuccessfully_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cote ajouté avec succès.
        /// </summary>
        internal static string RatingAddedSuccessfully_fr {
            get {
                return ResourceManager.GetString("RatingAddedSuccessfully_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral Program.
        /// </summary>
        internal static string ReferralPointsEmailSubject_en {
            get {
                return ResourceManager.GetString("ReferralPointsEmailSubject_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programme de référencement.
        /// </summary>
        internal static string ReferralPointsEmailSubject_fr {
            get {
                return ResourceManager.GetString("ReferralPointsEmailSubject_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password failed.
        /// </summary>
        internal static string ResetPasswordFailed_en {
            get {
                return ResourceManager.GetString("ResetPasswordFailed_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Échec de réinitialisation du mot de passe.
        /// </summary>
        internal static string ResetPasswordFailed_fr {
            get {
                return ResourceManager.GetString("ResetPasswordFailed_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward was deleted successfully.
        /// </summary>
        internal static string RewardDeleted_en {
            get {
                return ResourceManager.GetString("RewardDeleted_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La bonification a été supprimée avec succès.
        /// </summary>
        internal static string RewardDeleted_fr {
            get {
                return ResourceManager.GetString("RewardDeleted_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reward already exist for that date.
        /// </summary>
        internal static string RewardExistForThatDate_en {
            get {
                return ResourceManager.GetString("RewardExistForThatDate_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une bonification existe déjà pour cette date.
        /// </summary>
        internal static string RewardExistForThatDate_fr {
            get {
                return ResourceManager.GetString("RewardExistForThatDate_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward not found.
        /// </summary>
        internal static string RewardNotFound_en {
            get {
                return ResourceManager.GetString("RewardNotFound_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonification introuvable.
        /// </summary>
        internal static string RewardNotFound_fr {
            get {
                return ResourceManager.GetString("RewardNotFound_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base reward not set for that merchant.
        /// </summary>
        internal static string RewardNotSetForThatMerchant_en {
            get {
                return ResourceManager.GetString("RewardNotSetForThatMerchant_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La bonification de base n&apos;est pas défini pour ce marchand.
        /// </summary>
        internal static string RewardNotSetForThatMerchant_fr {
            get {
                return ResourceManager.GetString("RewardNotSetForThatMerchant_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social media user already used.
        /// </summary>
        internal static string SocialMediaUserAlreadyUsed_en {
            get {
                return ResourceManager.GetString("SocialMediaUserAlreadyUsed_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utlisateur pour ce média social déjà utilisé.
        /// </summary>
        internal static string SocialMediaUserAlreadyUsed_fr {
            get {
                return ResourceManager.GetString("SocialMediaUserAlreadyUsed_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting date is not a valid date.
        /// </summary>
        internal static string StartingDateNotAValidDate_en {
            get {
                return ResourceManager.GetString("StartingDateNotAValidDate_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de début n&apos;est pas valide.
        /// </summary>
        internal static string StartingDateNotAValidDate_fr {
            get {
                return ResourceManager.GetString("StartingDateNotAValidDate_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The starting date must be older than the ending date.
        /// </summary>
        internal static string StartingDateOlderThanEndingDate_en {
            get {
                return ResourceManager.GetString("StartingDateOlderThanEndingDate_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de début doit être antérieur à la date de fin.
        /// </summary>
        internal static string StartingDateOlderThanEndingDate_fr {
            get {
                return ResourceManager.GetString("StartingDateOlderThanEndingDate_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added.
        /// </summary>
        internal static string SuccessfullyAdded_en {
            get {
                return ResourceManager.GetString("SuccessfullyAdded_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouté avec succès.
        /// </summary>
        internal static string SuccessfullyAdded_fr {
            get {
                return ResourceManager.GetString("SuccessfullyAdded_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated successfully.
        /// </summary>
        internal static string SuccessfullyUpdated_en {
            get {
                return ResourceManager.GetString("SuccessfullyUpdated_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour réussie.
        /// </summary>
        internal static string SuccessfullyUpdated_fr {
            get {
                return ResourceManager.GetString("SuccessfullyUpdated_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated successfully, email validation sent to the new email address.
        /// </summary>
        internal static string SuccessfullyUpdatedEmailValidation_en {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedEmailValidation_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour réussie, une validation du courriel a été envoyé à la nouvelle adresse.
        /// </summary>
        internal static string SuccessfullyUpdatedEmailValidation_fr {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedEmailValidation_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction not found.
        /// </summary>
        internal static string TransactionNotFound_en {
            get {
                return ResourceManager.GetString("TransactionNotFound_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction introuvable.
        /// </summary>
        internal static string TransactionNotFound_fr {
            get {
                return ResourceManager.GetString("TransactionNotFound_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add banking information.
        /// </summary>
        internal static string UnableToAddBankingInfo_en {
            get {
                return ResourceManager.GetString("UnableToAddBankingInfo_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter les informations bancaires.
        /// </summary>
        internal static string UnableToAddBankingInfo_fr {
            get {
                return ResourceManager.GetString("UnableToAddBankingInfo_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add base reward.
        /// </summary>
        internal static string UnableToAddBaseReward_en {
            get {
                return ResourceManager.GetString("UnableToAddBaseReward_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter la bonification de base.
        /// </summary>
        internal static string UnableToAddBaseReward_fr {
            get {
                return ResourceManager.GetString("UnableToAddBaseReward_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add base reward calendar.
        /// </summary>
        internal static string UnableToAddBaseRewardCalendar_en {
            get {
                return ResourceManager.GetString("UnableToAddBaseRewardCalendar_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter le calendrier de bonification de base.
        /// </summary>
        internal static string UnableToAddBaseRewardCalendar_fr {
            get {
                return ResourceManager.GetString("UnableToAddBaseRewardCalendar_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add business hour.
        /// </summary>
        internal static string UnableToAddBusinessHour_en {
            get {
                return ResourceManager.GetString("UnableToAddBusinessHour_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter ces heures d&apos;ouverture.
        /// </summary>
        internal static string UnableToAddBusinessHour_fr {
            get {
                return ResourceManager.GetString("UnableToAddBusinessHour_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add the category.
        /// </summary>
        internal static string UnableToAddCategory_en {
            get {
                return ResourceManager.GetString("UnableToAddCategory_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter la catégorie.
        /// </summary>
        internal static string UnableToAddCategory_fr {
            get {
                return ResourceManager.GetString("UnableToAddCategory_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add this community.
        /// </summary>
        internal static string UnableToAddCommunity_en {
            get {
                return ResourceManager.GetString("UnableToAddCommunity_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter cette communauté.
        /// </summary>
        internal static string UnableToAddCommunity_fr {
            get {
                return ResourceManager.GetString("UnableToAddCommunity_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add credit card.
        /// </summary>
        internal static string UnableToAddCreditCard_en {
            get {
                return ResourceManager.GetString("UnableToAddCreditCard_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter la carte de crédit.
        /// </summary>
        internal static string UnableToAddCreditCard_fr {
            get {
                return ResourceManager.GetString("UnableToAddCreditCard_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add this holiday.
        /// </summary>
        internal static string UnableToAddHoliday_en {
            get {
                return ResourceManager.GetString("UnableToAddHoliday_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter ce congé.
        /// </summary>
        internal static string UnableToAddHoliday_fr {
            get {
                return ResourceManager.GetString("UnableToAddHoliday_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add merchant.
        /// </summary>
        internal static string UnableToAddMerchant_en {
            get {
                return ResourceManager.GetString("UnableToAddMerchant_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter le marchand.
        /// </summary>
        internal static string UnableToAddMerchant_fr {
            get {
                return ResourceManager.GetString("UnableToAddMerchant_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add merchant information.
        /// </summary>
        internal static string UnableToAddMerchantInformation_en {
            get {
                return ResourceManager.GetString("UnableToAddMerchantInformation_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter les informations du marchand.
        /// </summary>
        internal static string UnableToAddMerchantInformation_fr {
            get {
                return ResourceManager.GetString("UnableToAddMerchantInformation_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add notification.
        /// </summary>
        internal static string UnableToAddNotification_en {
            get {
                return ResourceManager.GetString("UnableToAddNotification_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter la notification.
        /// </summary>
        internal static string UnableToAddNotification_fr {
            get {
                return ResourceManager.GetString("UnableToAddNotification_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add rating.
        /// </summary>
        internal static string UnableToAddRating_en {
            get {
                return ResourceManager.GetString("UnableToAddRating_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter la cote.
        /// </summary>
        internal static string UnableToAddRating_fr {
            get {
                return ResourceManager.GetString("UnableToAddRating_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add reward.
        /// </summary>
        internal static string UnableToAddReward_en {
            get {
                return ResourceManager.GetString("UnableToAddReward_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter la bonification.
        /// </summary>
        internal static string UnableToAddReward_fr {
            get {
                return ResourceManager.GetString("UnableToAddReward_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add this tag to that merchant.
        /// </summary>
        internal static string UnableToAddTagToMerchant_en {
            get {
                return ResourceManager.GetString("UnableToAddTagToMerchant_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter ce tag au marchand.
        /// </summary>
        internal static string UnableToAddTagToMerchant_fr {
            get {
                return ResourceManager.GetString("UnableToAddTagToMerchant_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add user.
        /// </summary>
        internal static string UnableToAddUser_en {
            get {
                return ResourceManager.GetString("UnableToAddUser_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter l&apos;utilisateur.
        /// </summary>
        internal static string UnableToAddUser_fr {
            get {
                return ResourceManager.GetString("UnableToAddUser_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to approve merchant onboarding.
        /// </summary>
        internal static string UnableToApproveMerchant_en {
            get {
                return ResourceManager.GetString("UnableToApproveMerchant_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;approuver l&apos;approbation du marchand.
        /// </summary>
        internal static string UnableToApproveMerchant_fr {
            get {
                return ResourceManager.GetString("UnableToApproveMerchant_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete business hour.
        /// </summary>
        internal static string UnableToDeleteBusinessHour_en {
            get {
                return ResourceManager.GetString("UnableToDeleteBusinessHour_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer ces heures d&apos;ouverture.
        /// </summary>
        internal static string UnableToDeleteBusinessHour_fr {
            get {
                return ResourceManager.GetString("UnableToDeleteBusinessHour_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete credit card.
        /// </summary>
        internal static string UnableToDeleteCreditCard_en {
            get {
                return ResourceManager.GetString("UnableToDeleteCreditCard_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer la carte de crédit.
        /// </summary>
        internal static string UnableToDeleteCreditCard_fr {
            get {
                return ResourceManager.GetString("UnableToDeleteCreditCard_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete this holiday.
        /// </summary>
        internal static string UnableToDeleteHoliday_en {
            get {
                return ResourceManager.GetString("UnableToDeleteHoliday_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer le congé.
        /// </summary>
        internal static string UnableToDeleteHoliday_fr {
            get {
                return ResourceManager.GetString("UnableToDeleteHoliday_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete image.
        /// </summary>
        internal static string UnableToDeleteImage_en {
            get {
                return ResourceManager.GetString("UnableToDeleteImage_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer cette image.
        /// </summary>
        internal static string UnableToDeleteImage_fr {
            get {
                return ResourceManager.GetString("UnableToDeleteImage_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete member.
        /// </summary>
        internal static string UnableToDeleteMember_en {
            get {
                return ResourceManager.GetString("UnableToDeleteMember_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer le membre.
        /// </summary>
        internal static string UnableToDeleteMember_fr {
            get {
                return ResourceManager.GetString("UnableToDeleteMember_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete reward.
        /// </summary>
        internal static string UnableToDeleteReward_en {
            get {
                return ResourceManager.GetString("UnableToDeleteReward_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer la bonification.
        /// </summary>
        internal static string UnableToDeleteReward_fr {
            get {
                return ResourceManager.GetString("UnableToDeleteReward_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete user.
        /// </summary>
        internal static string UnableToDeleteUser_en {
            get {
                return ResourceManager.GetString("UnableToDeleteUser_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer l&apos;utilisateur.
        /// </summary>
        internal static string UnableToDeleteUser_fr {
            get {
                return ResourceManager.GetString("UnableToDeleteUser_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate the QRCode.
        /// </summary>
        internal static string UnableToGenerateQrCode_en {
            get {
                return ResourceManager.GetString("UnableToGenerateQrCode_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de générer le code QR.
        /// </summary>
        internal static string UnableToGenerateQrCode_fr {
            get {
                return ResourceManager.GetString("UnableToGenerateQrCode_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get invoice information.
        /// </summary>
        internal static string UnableToGetInvoice_en {
            get {
                return ResourceManager.GetString("UnableToGetInvoice_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;obtenir les informations de la facture.
        /// </summary>
        internal static string UnableToGetInvoice_fr {
            get {
                return ResourceManager.GetString("UnableToGetInvoice_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get reward.
        /// </summary>
        internal static string UnableToGetReward_en {
            get {
                return ResourceManager.GetString("UnableToGetReward_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;obtenir la bonification.
        /// </summary>
        internal static string UnableToGetReward_fr {
            get {
                return ResourceManager.GetString("UnableToGetReward_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get the statistics.
        /// </summary>
        internal static string UnableToGetStatistic_en {
            get {
                return ResourceManager.GetString("UnableToGetStatistic_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;obtenir les statistiques.
        /// </summary>
        internal static string UnableToGetStatistic_fr {
            get {
                return ResourceManager.GetString("UnableToGetStatistic_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get transaction history.
        /// </summary>
        internal static string UnableToGetTransactionHistory_en {
            get {
                return ResourceManager.GetString("UnableToGetTransactionHistory_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;obtenir l&apos;historique des transactions.
        /// </summary>
        internal static string UnableToGetTransactionHistory_fr {
            get {
                return ResourceManager.GetString("UnableToGetTransactionHistory_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to join community.
        /// </summary>
        internal static string UnableToJoinCommunity_en {
            get {
                return ResourceManager.GetString("UnableToJoinCommunity_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de joindre la communauté.
        /// </summary>
        internal static string UnableToJoinCommunity_fr {
            get {
                return ResourceManager.GetString("UnableToJoinCommunity_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login.
        /// </summary>
        internal static string UnableToLogin_en {
            get {
                return ResourceManager.GetString("UnableToLogin_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion impossible.
        /// </summary>
        internal static string UnableToLogin_fr {
            get {
                return ResourceManager.GetString("UnableToLogin_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to refuse merchant onboarding.
        /// </summary>
        internal static string UnableToRefuseMerchant_en {
            get {
                return ResourceManager.GetString("UnableToRefuseMerchant_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de refuser l&apos;approbation du marchand.
        /// </summary>
        internal static string UnableToRefuseMerchant_fr {
            get {
                return ResourceManager.GetString("UnableToRefuseMerchant_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove that tag from this merchant.
        /// </summary>
        internal static string UnableToRemoveMerchantTag_en {
            get {
                return ResourceManager.GetString("UnableToRemoveMerchantTag_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de retirer ce tag de ce marchand.
        /// </summary>
        internal static string UnableToRemoveMerchantTag_fr {
            get {
                return ResourceManager.GetString("UnableToRemoveMerchantTag_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the information.
        /// </summary>
        internal static string UnableToRetrieve_en {
            get {
                return ResourceManager.GetString("UnableToRetrieve_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de récupérer les informations.
        /// </summary>
        internal static string UnableToRetrieve_fr {
            get {
                return ResourceManager.GetString("UnableToRetrieve_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the community types.
        /// </summary>
        internal static string UnableToRetrieveCommunityType_en {
            get {
                return ResourceManager.GetString("UnableToRetrieveCommunityType_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de récupérer les types de communauté.
        /// </summary>
        internal static string UnableToRetrieveCommunityType_fr {
            get {
                return ResourceManager.GetString("UnableToRetrieveCommunityType_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de récupérer les informations de la facture.
        /// </summary>
        internal static string UnableToRetrieveInvoiceInfo_fr {
            get {
                return ResourceManager.GetString("UnableToRetrieveInvoiceInfo_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve point balance.
        /// </summary>
        internal static string UnableToRetrievePointBalance_en {
            get {
                return ResourceManager.GetString("UnableToRetrievePointBalance_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de récupérer la balance de points.
        /// </summary>
        internal static string UnableToRetrievePointBalance_fr {
            get {
                return ResourceManager.GetString("UnableToRetrievePointBalance_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the categories.
        /// </summary>
        internal static string UnableToRetrieveTheCategory_en {
            get {
                return ResourceManager.GetString("UnableToRetrieveTheCategory_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de récupérer les catégories.
        /// </summary>
        internal static string UnableToRetrieveTheCategory_fr {
            get {
                return ResourceManager.GetString("UnableToRetrieveTheCategory_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the communities.
        /// </summary>
        internal static string UnableToRetrieveTheCommunity_en {
            get {
                return ResourceManager.GetString("UnableToRetrieveTheCommunity_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de récupérer les communautés.
        /// </summary>
        internal static string UnableToRetrieveTheCommunity_fr {
            get {
                return ResourceManager.GetString("UnableToRetrieveTheCommunity_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the countries.
        /// </summary>
        internal static string UnableToRetrieveTheCountry_en {
            get {
                return ResourceManager.GetString("UnableToRetrieveTheCountry_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de récupérer les pays.
        /// </summary>
        internal static string UnableToRetrieveTheCountry_fr {
            get {
                return ResourceManager.GetString("UnableToRetrieveTheCountry_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the states.
        /// </summary>
        internal static string UnableToRetrieveTheState_en {
            get {
                return ResourceManager.GetString("UnableToRetrieveTheState_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de récupérer les provinces/états.
        /// </summary>
        internal static string UnableToRetrieveTheState_fr {
            get {
                return ResourceManager.GetString("UnableToRetrieveTheState_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the tags.
        /// </summary>
        internal static string UnableToRetrieveTheTag_en {
            get {
                return ResourceManager.GetString("UnableToRetrieveTheTag_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de récupérer les tags.
        /// </summary>
        internal static string UnableToRetrieveTheTag_fr {
            get {
                return ResourceManager.GetString("UnableToRetrieveTheTag_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de récupérer les transactions pour ce membre.
        /// </summary>
        internal static string UnableToRetrieveTransaction_fr {
            get {
                return ResourceManager.GetString("UnableToRetrieveTransaction_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve user information.
        /// </summary>
        internal static string UnableToRetrieveUser_en {
            get {
                return ResourceManager.GetString("UnableToRetrieveUser_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de récupérer les informations de l&apos;utilisateur.
        /// </summary>
        internal static string UnableToRetrieveUser_fr {
            get {
                return ResourceManager.GetString("UnableToRetrieveUser_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve invoice information.
        /// </summary>
        internal static string UnableToRetriveInvoiceInfo_en {
            get {
                return ResourceManager.GetString("UnableToRetriveInvoiceInfo_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the transactions for that member.
        /// </summary>
        internal static string UnableToRetriveTransaction_en {
            get {
                return ResourceManager.GetString("UnableToRetriveTransaction_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update banking information.
        /// </summary>
        internal static string UnableToUpdateBankingInfo_en {
            get {
                return ResourceManager.GetString("UnableToUpdateBankingInfo_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de modifier les informations bancaires.
        /// </summary>
        internal static string UnableToUpdateBankingInfo_fr {
            get {
                return ResourceManager.GetString("UnableToUpdateBankingInfo_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update business hour.
        /// </summary>
        internal static string UnableToUpdateBusinessHour_en {
            get {
                return ResourceManager.GetString("UnableToUpdateBusinessHour_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de modifier les heures d&apos;ouverture.
        /// </summary>
        internal static string UnableToUpdateBusinessHour_fr {
            get {
                return ResourceManager.GetString("UnableToUpdateBusinessHour_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the category.
        /// </summary>
        internal static string UnableToUpdateCategory_en {
            get {
                return ResourceManager.GetString("UnableToUpdateCategory_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de modifier la catégorie.
        /// </summary>
        internal static string UnableToUpdateCategory_fr {
            get {
                return ResourceManager.GetString("UnableToUpdateCategory_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update community.
        /// </summary>
        internal static string UnableToUpdateCommunity_en {
            get {
                return ResourceManager.GetString("UnableToUpdateCommunity_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de modifier la communauté.
        /// </summary>
        internal static string UnableToUpdateCommunity_fr {
            get {
                return ResourceManager.GetString("UnableToUpdateCommunity_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update credit card.
        /// </summary>
        internal static string UnableToUpdateCreditCard_en {
            get {
                return ResourceManager.GetString("UnableToUpdateCreditCard_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de modifier la carte de crédit.
        /// </summary>
        internal static string UnableToUpdateCreditCard_fr {
            get {
                return ResourceManager.GetString("UnableToUpdateCreditCard_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update this holiday.
        /// </summary>
        internal static string UnableToUpdateHoliday_en {
            get {
                return ResourceManager.GetString("UnableToUpdateHoliday_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de modifier ce congé.
        /// </summary>
        internal static string UnableToUpdateHoliday_fr {
            get {
                return ResourceManager.GetString("UnableToUpdateHoliday_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update image.
        /// </summary>
        internal static string UnableToUpdateImage_en {
            get {
                return ResourceManager.GetString("UnableToUpdateImage_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de modifier l&apos;image.
        /// </summary>
        internal static string UnableToUpdateImage_fr {
            get {
                return ResourceManager.GetString("UnableToUpdateImage_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update member.
        /// </summary>
        internal static string UnableToUpdateMember_en {
            get {
                return ResourceManager.GetString("UnableToUpdateMember_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de modifier le membre.
        /// </summary>
        internal static string UnableToUpdateMember_fr {
            get {
                return ResourceManager.GetString("UnableToUpdateMember_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update merchant.
        /// </summary>
        internal static string UnableToUpdateMerchant_en {
            get {
                return ResourceManager.GetString("UnableToUpdateMerchant_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de modifier le marchand.
        /// </summary>
        internal static string UnableToUpdateMerchant_fr {
            get {
                return ResourceManager.GetString("UnableToUpdateMerchant_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update reward.
        /// </summary>
        internal static string UnableToUpdateReward_en {
            get {
                return ResourceManager.GetString("UnableToUpdateReward_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de modifier la bonification.
        /// </summary>
        internal static string UnableToUpdateReward_fr {
            get {
                return ResourceManager.GetString("UnableToUpdateReward_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the tag.
        /// </summary>
        internal static string UnableToUpdateTag_en {
            get {
                return ResourceManager.GetString("UnableToUpdateTag_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de modifier la tag.
        /// </summary>
        internal static string UnableToUpdateTag_fr {
            get {
                return ResourceManager.GetString("UnableToUpdateTag_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update user.
        /// </summary>
        internal static string UnableToUpdateUser_en {
            get {
                return ResourceManager.GetString("UnableToUpdateUser_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de modifier l&apos;utilisateur.
        /// </summary>
        internal static string UnableToUpdateUser_fr {
            get {
                return ResourceManager.GetString("UnableToUpdateUser_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to validate email address.
        /// </summary>
        internal static string UnableToValidateEmailAddress_en {
            get {
                return ResourceManager.GetString("UnableToValidateEmailAddress_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de valider l&apos;adresse courriel.
        /// </summary>
        internal static string UnableToValidateEmailAddress_fr {
            get {
                return ResourceManager.GetString("UnableToValidateEmailAddress_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized to login.
        /// </summary>
        internal static string UnauthorizedToLogin_en {
            get {
                return ResourceManager.GetString("UnauthorizedToLogin_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion non autorisée.
        /// </summary>
        internal static string UnauthorizedToLogin_fr {
            get {
                return ResourceManager.GetString("UnauthorizedToLogin_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Unknown_en {
            get {
                return ResourceManager.GetString("Unknown_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune.
        /// </summary>
        internal static string Unknown_fr {
            get {
                return ResourceManager.GetString("Unknown_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User added successfully.
        /// </summary>
        internal static string UserAddedSuccessfully_en {
            get {
                return ResourceManager.GetString("UserAddedSuccessfully_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur ajouté avec succès.
        /// </summary>
        internal static string UserAddedSuccessfully_fr {
            get {
                return ResourceManager.GetString("UserAddedSuccessfully_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was successfully deleted.
        /// </summary>
        internal static string UserDeleted_en {
            get {
                return ResourceManager.GetString("UserDeleted_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;utilisateur a été supprimé avec succès.
        /// </summary>
        internal static string UserDeleted_fr {
            get {
                return ResourceManager.GetString("UserDeleted_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access user information.
        /// </summary>
        internal static string UserInfoNotAccessible_en {
            get {
                return ResourceManager.GetString("UserInfoNotAccessible_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;accéder les informations de l&apos;utilisateur.
        /// </summary>
        internal static string UserInfoNotAccessible_fr {
            get {
                return ResourceManager.GetString("UserInfoNotAccessible_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string UserNotFound_en {
            get {
                return ResourceManager.GetString("UserNotFound_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur introuvable.
        /// </summary>
        internal static string UserNotFound_fr {
            get {
                return ResourceManager.GetString("UserNotFound_fr", resourceCulture);
            }
        }
    }
}
