using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IMS.Common.Core.Entities.Transax
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:2.0.50727.8009
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.1432.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "EnrollUser", Namespace = "", IsNullable = false)]
    public partial class TransaxEnrollUser
    {

        private string idField;

        private string programIdField;

        private string cardNonFinancialIdField;

        private string startDateField;

        private string endDateField;

        private string commentsSubscriptionField;

        private string priceField;

        private string financialTransactionField;

        private string pointsBalanceField;

        private string programLevelField;

        private string financialCardAssociatedField;

        private string giftBalanceField;

        private string ewalletBalanceField;

        private string statusSubscriptionField;

        private string subscriptionCreationField;

        private string subscriptionModificationField;

        private string idContractOSPField;

        private string outSidePartnerField;

        private string commisionPerRegistryField;

        private string commisionPerTransactionLoyaltyField;

        private string commisionPerEwalletTransactionField;

        private string commisionPerGiftTransactionField;

        private string commisionPerPointExpendedField;

        private string commisionPerGiftAmountField;

        private string commisionPerPointAcquiredField;

        private string ospContractStatusField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string programId
        {
            get
            {
                return this.programIdField;
            }
            set
            {
                this.programIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cardNonFinancialId
        {
            get
            {
                return this.cardNonFinancialIdField;
            }
            set
            {
                this.cardNonFinancialIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string startDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string endDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string commentsSubscription
        {
            get
            {
                return this.commentsSubscriptionField;
            }
            set
            {
                this.commentsSubscriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string financialTransaction
        {
            get
            {
                return this.financialTransactionField;
            }
            set
            {
                this.financialTransactionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pointsBalance
        {
            get
            {
                return this.pointsBalanceField;
            }
            set
            {
                this.pointsBalanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string programLevel
        {
            get
            {
                return this.programLevelField;
            }
            set
            {
                this.programLevelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string financialCardAssociated
        {
            get
            {
                return this.financialCardAssociatedField;
            }
            set
            {
                this.financialCardAssociatedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string giftBalance
        {
            get
            {
                return this.giftBalanceField;
            }
            set
            {
                this.giftBalanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ewalletBalance
        {
            get
            {
                return this.ewalletBalanceField;
            }
            set
            {
                this.ewalletBalanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string statusSubscription
        {
            get
            {
                return this.statusSubscriptionField;
            }
            set
            {
                this.statusSubscriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string subscriptionCreation
        {
            get
            {
                return this.subscriptionCreationField;
            }
            set
            {
                this.subscriptionCreationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string subscriptionModification
        {
            get
            {
                return this.subscriptionModificationField;
            }
            set
            {
                this.subscriptionModificationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string idContractOSP
        {
            get
            {
                return this.idContractOSPField;
            }
            set
            {
                this.idContractOSPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string outSidePartner
        {
            get
            {
                return this.outSidePartnerField;
            }
            set
            {
                this.outSidePartnerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string commisionPerRegistry
        {
            get
            {
                return this.commisionPerRegistryField;
            }
            set
            {
                this.commisionPerRegistryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string commisionPerTransactionLoyalty
        {
            get
            {
                return this.commisionPerTransactionLoyaltyField;
            }
            set
            {
                this.commisionPerTransactionLoyaltyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string commisionPerEwalletTransaction
        {
            get
            {
                return this.commisionPerEwalletTransactionField;
            }
            set
            {
                this.commisionPerEwalletTransactionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string commisionPerGiftTransaction
        {
            get
            {
                return this.commisionPerGiftTransactionField;
            }
            set
            {
                this.commisionPerGiftTransactionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string commisionPerPointExpended
        {
            get
            {
                return this.commisionPerPointExpendedField;
            }
            set
            {
                this.commisionPerPointExpendedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string commisionPerGiftAmount
        {
            get
            {
                return this.commisionPerGiftAmountField;
            }
            set
            {
                this.commisionPerGiftAmountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string commisionPerPointAcquired
        {
            get
            {
                return this.commisionPerPointAcquiredField;
            }
            set
            {
                this.commisionPerPointAcquiredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ospContractStatus
        {
            get
            {
                return this.ospContractStatusField;
            }
            set
            {
                this.ospContractStatusField = value;
            }
        }
    }
}
