using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IMS.Common.Core.Entities.Transax
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:2.0.50727.8009
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.1432.
    // 

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class TransaxTransferRS
    {

        private TransaxRSNonFinancialTransactionTransfer[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NonFinancialTransactionTransfer", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TransaxRSNonFinancialTransactionTransfer[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        public partial class TransaxRSNonFinancialTransactionTransfer
        {

            private string idTransactionField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string idTransaction
            {
                get
                {
                    return this.idTransactionField;
                }
                set
                {
                    this.idTransactionField = value;
                }
            }
        }
    }
}
