//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", ElementName="TransaxRS", IsNullable = false)]
public partial class TransaxLoginWithTerminalRS
{

    //private object[] itemsField;

    ///// <remarks/>
    //[System.Xml.Serialization.XmlElementAttribute("Entity", typeof(TransaxRSEntity), ElementName="Entity", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //[System.Xml.Serialization.XmlElementAttribute("Location", typeof(TransaxRSLocation), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //[System.Xml.Serialization.XmlElementAttribute("Merchant", typeof(TransaxRSMerchant), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //[System.Xml.Serialization.XmlElementAttribute("System", typeof(TransaxRSSystem), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //[System.Xml.Serialization.XmlElementAttribute("Terminal", typeof(TransaxRSTerminal), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //[System.Xml.Serialization.XmlElementAttribute("User", typeof(TransaxRSUser), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //[System.Xml.Serialization.XmlElementAttribute("tax_0", typeof(TransaxRSTax_0), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //[System.Xml.Serialization.XmlElementAttribute("tax_1", typeof(TransaxRSTax_1), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //public object[] Items
    //{
    //    get
    //    {
    //        return this.itemsField;
    //    }
    //    set
    //    {
    //        this.itemsField = value;
    //    }
    //}

    private TransaxRSEntity entity;
    private TransaxRSLocation location;
    private TransaxRSMerchant merchant;
    private TransaxRSSystem system;
    private TransaxRSTerminal terminal;
    private TransaxRSUser user;
    private TransaxRSTax_0 tax_0;
    private TransaxRSTax_1 tax_1;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Entity", typeof(TransaxRSEntity), ElementName = "Entity", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TransaxRSEntity Entity
    {
        get
        {
            return this.entity;
        }
        set
        {
            this.entity = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Location", typeof(TransaxRSLocation), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TransaxRSLocation Location
    {
        get
        {
            return this.location;
        }
        set
        {
            this.location = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Merchant", typeof(TransaxRSMerchant), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TransaxRSMerchant Merchant
    {
        get
        {
            return this.merchant;
        }
        set
        {
            this.merchant = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("System", typeof(TransaxRSSystem), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TransaxRSSystem _System
    {
        get
        {
            return this.system;
        }
        set
        {
            this.system = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Terminal", typeof(TransaxRSTerminal), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TransaxRSTerminal Terminal
    {
        get
        {
            return this.terminal;
        }
        set
        {
            this.terminal = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("User", typeof(TransaxRSUser), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TransaxRSUser User
    {
        get
        {
            return this.user;
        }
        set
        {
            this.user = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tax_0", typeof(TransaxRSTax_0), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TransaxRSTax_0 Tax_0
    {
        get
        {
            return this.tax_0;
        }
        set
        {
            this.tax_0 = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tax_1", typeof(TransaxRSTax_1), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TransaxRSTax_1 Tax_1
    {
        get
        {
            return this.tax_1;
        }
        set
        {
            this.tax_1 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TransaxRSEntity
{

    private string idField;

    private string providerIdField;

    private string parentIdField;

    private string userAdminIdField;

    private string nameField;

    private string statusField;

    private string emailField;

    private string sloganField;

    private string imageEntityField;

    private string cifField;

    private string countryEntityField;

    private string regionField;

    private string cityField;

    private string postalcodeEntityField;

    private string streetAddressField;

    private string numberAddressField;

    private string floorAddressField;

    private string latitudeField;

    private string longitudeField;

    private string interestField;

    private string currencyField;

    private string tipsEnabledField;

    private string tips1Field;

    private string tips2Field;

    private string tips3Field;

    private string categoryEntityField;

    private string invoiceEmailEntityField;

    private string invoiceEmailPasswordField;

    private string invoiceEmailPortField;

    private string mainPromoField;

    private string phoneField;

    private string userField;

    private string userDescField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Id")]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string providerId
    {
        get
        {
            return this.providerIdField;
        }
        set
        {
            this.providerIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string parentId
    {
        get
        {
            return this.parentIdField;
        }
        set
        {
            this.parentIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string userAdminId
    {
        get
        {
            return this.userAdminIdField;
        }
        set
        {
            this.userAdminIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string slogan
    {
        get
        {
            return this.sloganField;
        }
        set
        {
            this.sloganField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string imageEntity
    {
        get
        {
            return this.imageEntityField;
        }
        set
        {
            this.imageEntityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cif
    {
        get
        {
            return this.cifField;
        }
        set
        {
            this.cifField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string countryEntity
    {
        get
        {
            return this.countryEntityField;
        }
        set
        {
            this.countryEntityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string region
    {
        get
        {
            return this.regionField;
        }
        set
        {
            this.regionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string city
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string postalcodeEntity
    {
        get
        {
            return this.postalcodeEntityField;
        }
        set
        {
            this.postalcodeEntityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string streetAddress
    {
        get
        {
            return this.streetAddressField;
        }
        set
        {
            this.streetAddressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string numberAddress
    {
        get
        {
            return this.numberAddressField;
        }
        set
        {
            this.numberAddressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string floorAddress
    {
        get
        {
            return this.floorAddressField;
        }
        set
        {
            this.floorAddressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string latitude
    {
        get
        {
            return this.latitudeField;
        }
        set
        {
            this.latitudeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string longitude
    {
        get
        {
            return this.longitudeField;
        }
        set
        {
            this.longitudeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string interest
    {
        get
        {
            return this.interestField;
        }
        set
        {
            this.interestField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string currency
    {
        get
        {
            return this.currencyField;
        }
        set
        {
            this.currencyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tipsEnabled
    {
        get
        {
            return this.tipsEnabledField;
        }
        set
        {
            this.tipsEnabledField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tips1
    {
        get
        {
            return this.tips1Field;
        }
        set
        {
            this.tips1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tips2
    {
        get
        {
            return this.tips2Field;
        }
        set
        {
            this.tips2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tips3
    {
        get
        {
            return this.tips3Field;
        }
        set
        {
            this.tips3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string categoryEntity
    {
        get
        {
            return this.categoryEntityField;
        }
        set
        {
            this.categoryEntityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string invoiceEmailEntity
    {
        get
        {
            return this.invoiceEmailEntityField;
        }
        set
        {
            this.invoiceEmailEntityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string invoiceEmailPassword
    {
        get
        {
            return this.invoiceEmailPasswordField;
        }
        set
        {
            this.invoiceEmailPasswordField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string invoiceEmailPort
    {
        get
        {
            return this.invoiceEmailPortField;
        }
        set
        {
            this.invoiceEmailPortField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mainPromo
    {
        get
        {
            return this.mainPromoField;
        }
        set
        {
            this.mainPromoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string User
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UserDesc
    {
        get
        {
            return this.userDescField;
        }
        set
        {
            this.userDescField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TransaxRSLocation
{

    private string idField;

    private string providerIdField;

    private string parentIdField;

    private string userAdminIdField;

    private string nameField;

    private string statusField;

    private string emailField;

    private string sloganField;

    private string imageEntityField;

    private string cifField;

    private string countryEntityField;

    private string regionField;

    private string cityField;

    private string postalcodeEntityField;

    private string streetAddressField;

    private string numberAddressField;

    private string floorAddressField;

    private string latitudeField;

    private string longitudeField;

    private string interestField;

    private string currencyField;

    private string tipsEnabledField;

    private string tips1Field;

    private string tips2Field;

    private string tips3Field;

    private string categoryEntityField;

    private string invoiceEmailEntityField;

    private string invoiceEmailPasswordField;

    private string invoiceEmailPortField;

    private string mainPromoField;

    private string phoneField;

    private string userField;

    private string userDescField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string providerId
    {
        get
        {
            return this.providerIdField;
        }
        set
        {
            this.providerIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string parentId
    {
        get
        {
            return this.parentIdField;
        }
        set
        {
            this.parentIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string userAdminId
    {
        get
        {
            return this.userAdminIdField;
        }
        set
        {
            this.userAdminIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string slogan
    {
        get
        {
            return this.sloganField;
        }
        set
        {
            this.sloganField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string imageEntity
    {
        get
        {
            return this.imageEntityField;
        }
        set
        {
            this.imageEntityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cif
    {
        get
        {
            return this.cifField;
        }
        set
        {
            this.cifField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string countryEntity
    {
        get
        {
            return this.countryEntityField;
        }
        set
        {
            this.countryEntityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string region
    {
        get
        {
            return this.regionField;
        }
        set
        {
            this.regionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string city
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string postalcodeEntity
    {
        get
        {
            return this.postalcodeEntityField;
        }
        set
        {
            this.postalcodeEntityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string streetAddress
    {
        get
        {
            return this.streetAddressField;
        }
        set
        {
            this.streetAddressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string numberAddress
    {
        get
        {
            return this.numberAddressField;
        }
        set
        {
            this.numberAddressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string floorAddress
    {
        get
        {
            return this.floorAddressField;
        }
        set
        {
            this.floorAddressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string latitude
    {
        get
        {
            return this.latitudeField;
        }
        set
        {
            this.latitudeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string longitude
    {
        get
        {
            return this.longitudeField;
        }
        set
        {
            this.longitudeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string interest
    {
        get
        {
            return this.interestField;
        }
        set
        {
            this.interestField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string currency
    {
        get
        {
            return this.currencyField;
        }
        set
        {
            this.currencyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tipsEnabled
    {
        get
        {
            return this.tipsEnabledField;
        }
        set
        {
            this.tipsEnabledField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tips1
    {
        get
        {
            return this.tips1Field;
        }
        set
        {
            this.tips1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tips2
    {
        get
        {
            return this.tips2Field;
        }
        set
        {
            this.tips2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tips3
    {
        get
        {
            return this.tips3Field;
        }
        set
        {
            this.tips3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string categoryEntity
    {
        get
        {
            return this.categoryEntityField;
        }
        set
        {
            this.categoryEntityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string invoiceEmailEntity
    {
        get
        {
            return this.invoiceEmailEntityField;
        }
        set
        {
            this.invoiceEmailEntityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string invoiceEmailPassword
    {
        get
        {
            return this.invoiceEmailPasswordField;
        }
        set
        {
            this.invoiceEmailPasswordField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string invoiceEmailPort
    {
        get
        {
            return this.invoiceEmailPortField;
        }
        set
        {
            this.invoiceEmailPortField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mainPromo
    {
        get
        {
            return this.mainPromoField;
        }
        set
        {
            this.mainPromoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string User
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UserDesc
    {
        get
        {
            return this.userDescField;
        }
        set
        {
            this.userDescField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TransaxRSMerchant
{

    private string idField;

    private string providerIdField;

    private string parentIdField;

    private string userAdminIdField;

    private string userField;

    private string userDescField;

    private string nameField;

    private string statusField;

    private string emailField;

    private string sloganField;

    private string imageEntityField;

    private string cifField;

    private string countryEntityField;

    private string regionField;

    private string cityField;

    private string postalcodeEntityField;

    private string streetAddressField;

    private string numberAddressField;

    private string floorAddressField;

    private string latitudeField;

    private string longitudeField;

    private string interestField;

    private string currencyField;

    private string tipsEnabledField;

    private string tips1Field;

    private string tips2Field;

    private string tips3Field;

    private string categoryEntityField;

    private string invoiceEmailEntityField;

    private string invoiceEmailPasswordField;

    private string invoiceEmailPortField;

    private string mainPromoField;

    private string phoneField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string providerId
    {
        get
        {
            return this.providerIdField;
        }
        set
        {
            this.providerIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string parentId
    {
        get
        {
            return this.parentIdField;
        }
        set
        {
            this.parentIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string userAdminId
    {
        get
        {
            return this.userAdminIdField;
        }
        set
        {
            this.userAdminIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string User
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UserDesc
    {
        get
        {
            return this.userDescField;
        }
        set
        {
            this.userDescField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string slogan
    {
        get
        {
            return this.sloganField;
        }
        set
        {
            this.sloganField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string imageEntity
    {
        get
        {
            return this.imageEntityField;
        }
        set
        {
            this.imageEntityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cif
    {
        get
        {
            return this.cifField;
        }
        set
        {
            this.cifField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string countryEntity
    {
        get
        {
            return this.countryEntityField;
        }
        set
        {
            this.countryEntityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string region
    {
        get
        {
            return this.regionField;
        }
        set
        {
            this.regionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string city
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string postalcodeEntity
    {
        get
        {
            return this.postalcodeEntityField;
        }
        set
        {
            this.postalcodeEntityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string streetAddress
    {
        get
        {
            return this.streetAddressField;
        }
        set
        {
            this.streetAddressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string numberAddress
    {
        get
        {
            return this.numberAddressField;
        }
        set
        {
            this.numberAddressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string floorAddress
    {
        get
        {
            return this.floorAddressField;
        }
        set
        {
            this.floorAddressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string latitude
    {
        get
        {
            return this.latitudeField;
        }
        set
        {
            this.latitudeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string longitude
    {
        get
        {
            return this.longitudeField;
        }
        set
        {
            this.longitudeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string interest
    {
        get
        {
            return this.interestField;
        }
        set
        {
            this.interestField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string currency
    {
        get
        {
            return this.currencyField;
        }
        set
        {
            this.currencyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tipsEnabled
    {
        get
        {
            return this.tipsEnabledField;
        }
        set
        {
            this.tipsEnabledField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tips1
    {
        get
        {
            return this.tips1Field;
        }
        set
        {
            this.tips1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tips2
    {
        get
        {
            return this.tips2Field;
        }
        set
        {
            this.tips2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tips3
    {
        get
        {
            return this.tips3Field;
        }
        set
        {
            this.tips3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string categoryEntity
    {
        get
        {
            return this.categoryEntityField;
        }
        set
        {
            this.categoryEntityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string invoiceEmailEntity
    {
        get
        {
            return this.invoiceEmailEntityField;
        }
        set
        {
            this.invoiceEmailEntityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string invoiceEmailPassword
    {
        get
        {
            return this.invoiceEmailPasswordField;
        }
        set
        {
            this.invoiceEmailPasswordField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string invoiceEmailPort
    {
        get
        {
            return this.invoiceEmailPortField;
        }
        set
        {
            this.invoiceEmailPortField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mainPromo
    {
        get
        {
            return this.mainPromoField;
        }
        set
        {
            this.mainPromoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TransaxRSSystem
{

    private string phostipField;

    private string shostipField;

    private string phostPortField;

    private string shostPortField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string phostip
    {
        get
        {
            return this.phostipField;
        }
        set
        {
            this.phostipField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shostip
    {
        get
        {
            return this.shostipField;
        }
        set
        {
            this.shostipField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string phostPort
    {
        get
        {
            return this.phostPortField;
        }
        set
        {
            this.phostPortField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shostPort
    {
        get
        {
            return this.shostPortField;
        }
        set
        {
            this.shostPortField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TransaxRSTerminal
{

    private string extraDescriptionField;

    private string e10001Field;

    private string e10002Field;

    private string e10003Field;

    private string e10004Field;

    private string e10005Field;

    private string e10006Field;

    private string e10007Field;

    private string e10008Field;

    private string e10009Field;

    private string e10010Field;

    private string e10011Field;

    private string e10012Field;

    private string e10013Field;

    private string e10014Field;

    private string e10015Field;

    private string e10016Field;

    private string e10017Field;

    private string e10018Field;

    private string e10019Field;

    private string idField;

    private string entityIdField;

    private string readerField;

    private string statusField;

    private string serialNumberField;

    private string nameField;

    private string currencyCodeField;

    private string PINValidationField;

    private string minAmountForPINField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string extraDescription
    {
        get
        {
            return this.extraDescriptionField;
        }
        set
        {
            this.extraDescriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string E10001
    {
        get
        {
            return this.e10001Field;
        }
        set
        {
            this.e10001Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string E10002
    {
        get
        {
            return this.e10002Field;
        }
        set
        {
            this.e10002Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string E10003
    {
        get
        {
            return this.e10003Field;
        }
        set
        {
            this.e10003Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string E10004
    {
        get
        {
            return this.e10004Field;
        }
        set
        {
            this.e10004Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string E10005
    {
        get
        {
            return this.e10005Field;
        }
        set
        {
            this.e10005Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string E10006
    {
        get
        {
            return this.e10006Field;
        }
        set
        {
            this.e10006Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string E10007
    {
        get
        {
            return this.e10007Field;
        }
        set
        {
            this.e10007Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string E10008
    {
        get
        {
            return this.e10008Field;
        }
        set
        {
            this.e10008Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string E10009
    {
        get
        {
            return this.e10009Field;
        }
        set
        {
            this.e10009Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string E10010
    {
        get
        {
            return this.e10010Field;
        }
        set
        {
            this.e10010Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string E10011
    {
        get
        {
            return this.e10011Field;
        }
        set
        {
            this.e10011Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string E10012
    {
        get
        {
            return this.e10012Field;
        }
        set
        {
            this.e10012Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string E10013
    {
        get
        {
            return this.e10013Field;
        }
        set
        {
            this.e10013Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string E10014
    {
        get
        {
            return this.e10014Field;
        }
        set
        {
            this.e10014Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string E10015
    {
        get
        {
            return this.e10015Field;
        }
        set
        {
            this.e10015Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string E10016
    {
        get
        {
            return this.e10016Field;
        }
        set
        {
            this.e10016Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string E10017
    {
        get
        {
            return this.e10017Field;
        }
        set
        {
            this.e10017Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string E10018
    {
        get
        {
            return this.e10018Field;
        }
        set
        {
            this.e10018Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string E10019
    {
        get
        {
            return this.e10019Field;
        }
        set
        {
            this.e10019Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string entityId
    {
        get
        {
            return this.entityIdField;
        }
        set
        {
            this.entityIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string reader
    {
        get
        {
            return this.readerField;
        }
        set
        {
            this.readerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string serialNumber
    {
        get
        {
            return this.serialNumberField;
        }
        set
        {
            this.serialNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string currencyCode
    {
        get
        {
            return this.currencyCodeField;
        }
        set
        {
            this.currencyCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PINValidation
    {
        get
        {
            return this.PINValidationField;
        }
        set
        {
            this.PINValidationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string minAmountForPIN
    {
        get
        {
            return this.minAmountForPINField;
        }
        set
        {
            this.minAmountForPINField = value;
        }
    }
}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
//public partial class TransaxRSUser
//{

//    private string idField;

//    private string statusField;

//    private string nameField;

//    private string surnamesField;

//    private string emailField;

//    private string languageField;

//    private string countryField;

//    private string regionField;

//    private string cityField;

//    private string postalCodeField;

//    private string streetAddressField;

//    private string numberAddressField;

//    private string floorAddressField;

//    private string phoneField;

//    private string birthDayField;

//    private string citizenField;

//    private string civilStatusField;

//    private string addressSecondaryField;

//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string id
//    {
//        get
//        {
//            return this.idField;
//        }
//        set
//        {
//            this.idField = value;
//        }
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string status
//    {
//        get
//        {
//            return this.statusField;
//        }
//        set
//        {
//            this.statusField = value;
//        }
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string name
//    {
//        get
//        {
//            return this.nameField;
//        }
//        set
//        {
//            this.nameField = value;
//        }
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string surnames
//    {
//        get
//        {
//            return this.surnamesField;
//        }
//        set
//        {
//            this.surnamesField = value;
//        }
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string email
//    {
//        get
//        {
//            return this.emailField;
//        }
//        set
//        {
//            this.emailField = value;
//        }
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string language
//    {
//        get
//        {
//            return this.languageField;
//        }
//        set
//        {
//            this.languageField = value;
//        }
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string country
//    {
//        get
//        {
//            return this.countryField;
//        }
//        set
//        {
//            this.countryField = value;
//        }
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string region
//    {
//        get
//        {
//            return this.regionField;
//        }
//        set
//        {
//            this.regionField = value;
//        }
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string city
//    {
//        get
//        {
//            return this.cityField;
//        }
//        set
//        {
//            this.cityField = value;
//        }
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string postalCode
//    {
//        get
//        {
//            return this.postalCodeField;
//        }
//        set
//        {
//            this.postalCodeField = value;
//        }
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string streetAddress
//    {
//        get
//        {
//            return this.streetAddressField;
//        }
//        set
//        {
//            this.streetAddressField = value;
//        }
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string numberAddress
//    {
//        get
//        {
//            return this.numberAddressField;
//        }
//        set
//        {
//            this.numberAddressField = value;
//        }
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string floorAddress
//    {
//        get
//        {
//            return this.floorAddressField;
//        }
//        set
//        {
//            this.floorAddressField = value;
//        }
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string phone
//    {
//        get
//        {
//            return this.phoneField;
//        }
//        set
//        {
//            this.phoneField = value;
//        }
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string birthDay
//    {
//        get
//        {
//            return this.birthDayField;
//        }
//        set
//        {
//            this.birthDayField = value;
//        }
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string citizen
//    {
//        get
//        {
//            return this.citizenField;
//        }
//        set
//        {
//            this.citizenField = value;
//        }
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string civilStatus
//    {
//        get
//        {
//            return this.civilStatusField;
//        }
//        set
//        {
//            this.civilStatusField = value;
//        }
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string addressSecondary
//    {
//        get
//        {
//            return this.addressSecondaryField;
//        }
//        set
//        {
//            this.addressSecondaryField = value;
//        }
//    }
//}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TransaxRSTax_0
{

    private string idField;

    private string statusField;

    private string nameField;

    private string percentField;

    private string absoluteField;

    private string minimumField;

    private string byDefaultField;

    private string priorityField;

    private string regionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string percent
    {
        get
        {
            return this.percentField;
        }
        set
        {
            this.percentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string absolute
    {
        get
        {
            return this.absoluteField;
        }
        set
        {
            this.absoluteField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string minimum
    {
        get
        {
            return this.minimumField;
        }
        set
        {
            this.minimumField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string byDefault
    {
        get
        {
            return this.byDefaultField;
        }
        set
        {
            this.byDefaultField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string priority
    {
        get
        {
            return this.priorityField;
        }
        set
        {
            this.priorityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string region
    {
        get
        {
            return this.regionField;
        }
        set
        {
            this.regionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TransaxRSTax_1
{

    private string idField;

    private string regionField;

    private string statusField;

    private string nameField;

    private string percentField;

    private string absoluteField;

    private string minimumField;

    private string byDefaultField;

    private string priorityField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string region
    {
        get
        {
            return this.regionField;
        }
        set
        {
            this.regionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string percent
    {
        get
        {
            return this.percentField;
        }
        set
        {
            this.percentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string absolute
    {
        get
        {
            return this.absoluteField;
        }
        set
        {
            this.absoluteField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string minimum
    {
        get
        {
            return this.minimumField;
        }
        set
        {
            this.minimumField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string byDefault
    {
        get
        {
            return this.byDefaultField;
        }
        set
        {
            this.byDefaultField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string priority
    {
        get
        {
            return this.priorityField;
        }
        set
        {
            this.priorityField = value;
        }
    }
}
