using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IMS.Common.Core.Enumerations
{
    public enum IMSTranferMessage
    {
        //Parameter level
        MISSING_BASE_AMOUNT = 1,
        MISSING_ADDITIONAL_AMOUNT = 2,
        MISSING_APPROVED_AMOUNT = 3,
        MISSING_ENTITY_ID = 4,
        MISSING_LOCAL_DATETIME = 5,
        MISSING_ACQUIRER_REFERENCE = 6,
        MISSING_CURRENCY_ID = 7,
        MISSING_TRANSACTION_TYPE_ID = 8,
        MISSING_LEG_TRANSACTION_ID = 9,
        MISSING_CREDIT_CARD_ID = 10,

        //Logical level
        GET_TIMEZONE_INFO_FOR_ENTRY_ERROR = 100,
        GET_VENDOR_INFO_FAILED = 101,
        GET_ENTERPRISE_INFO_FAILED = 102,
        GET_LOCATION_INFO_FAILED = 103,
        GET_SALESREP_INFO_FAILED = 104,
        GET_TERMINAL_INFO_FAILED = 105,
        GET_CONTRACT_INFO_FAILED = 106,
        
        CREATE_HEADER_IMS_FAILED = 200,
        ADJUST_HEADER_IMS_FAILED = 201,
        CREATE_DETAIL_PACKAGE_COMMISSION_IMS_FAILED = 202,
        CREATE_DETAIL_TAX_IMS_FAILED = 203,
        CREATE_HEADER_MERCHANT_FAILED = 210,
        ADJUST_HEADER_MERCHANT_FAILED = 211,
        CREATE_DETAIL_MERCHANT_REIMBURSMENT_FAILED = 212,
        CREATE_DETAIL_TAX_MERCHANT_FAILED = 213,
        CREATE_DETAIL_TIP_MERCHANT_FAILED = 214,
        CREATE_HEADER_SALESREP_FAILED = 220,
        ADJUST_HEADER_SALESREP_FAILED = 221,
        CREATE_DETAIL_SALESREP_COMMISSION_FAILED = 222,
        CREATE_HEADER_OUTSIDEREP_FAILED = 230,
        ADJUST_HEADER_OUTSIDEREP_FAILED = 231,
        CREATE_DETAIL_OUTSIDEREP_COMMISSION_FAILED = 232,
        CREATE_HEADER_OUTSIDECHANNEL_FAILED = 240,
        ADJUST_HEADER_OUTSIDECHANNEL_FAILED = 241,
        CREATE_DETAIL_OUTSIDECHANNEL_COMMISSION_FAILED = 242
    }
}
