//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Badge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Badge()
        {
            this.BadgeTranslations = new HashSet<BadgeTranslation>();
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public int Id { get; set; }
        public int BadgeCategoryId { get; set; }
        public Nullable<int> TagId { get; set; }
        public int Levels { get; set; }
        public int Stars { get; set; }
        public int SendAfter { get; set; }
        public string Filepath { get; set; }
        public int CampaignTypeId { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual BadgeCategory BadgeCategory { get; set; }
        public virtual CampaignType CampaignType { get; set; }
        public virtual tag tag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BadgeTranslation> BadgeTranslations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
