//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchCloseLog
    {
        public int Id { get; set; }
        public string merchantId { get; set; }
        public string terminalId { get; set; }
        public System.DateTime batchClosingDate { get; set; }
        public string responseCode { get; set; }
        public string clerkMessageResponse { get; set; }
        public string batchNumberSequence { get; set; }
        public string batchTotal { get; set; }
        public string traceNumber { get; set; }
        public string batchStartTime { get; set; }
        public string batchEndTime { get; set; }
        public string trxcapResponseCode { get; set; }
    }
}
