//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractLocation
    {
        public long Id { get; set; }
        public long ContractId { get; set; }
        public long LocationId { get; set; }
        public string TransaxEnterpriseContractId { get; set; }
        public string TransaxSalesRepContractId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Location Location { get; set; }
    }
}
