//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.ContractCommissions = new HashSet<ContractCommission>();
            this.ContractLocations = new HashSet<ContractLocation>();
            this.Packages = new HashSet<Package>();
        }
    
        public long Id { get; set; }
        public long EnterpriseId { get; set; }
        public Nullable<long> MerchantId { get; set; }
        public int IMS_LineItemId { get; set; }
        public string ContractNumber { get; set; }
        public decimal Amount { get; set; }
        public int CurrencyId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime ContractStartDate { get; set; }
        public System.DateTime ContractEndDate { get; set; }
        public Nullable<long> SalesRepId { get; set; }
        public Nullable<double> CommissionRate { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractCommission> ContractCommissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractLocation> ContractLocations { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Enterprise Enterprise { get; set; }
        public virtual IMS_LineItem IMS_LineItem { get; set; }
        public virtual SalesRep SalesRep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package> Packages { get; set; }
        public virtual Merchant Merchant { get; set; }
    }
}
