//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCardIssuer
    {
        public int Id { get; set; }
        public string Issuer { get; set; }
        public int IIN_from { get; set; }
        public int IIN_to { get; set; }
        public int Min_Length { get; set; }
        public int Max_Length { get; set; }
        public bool LunhValidation { get; set; }
        public int CreditCardTypeId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CreditCardType CreditCardType { get; set; }
    }
}
