//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceRequest
    {
        public long Id { get; set; }
        public long MemberId { get; set; }
        public long IMSMembershipId { get; set; }
        public int DeviceTypeId { get; set; }
        public int DeviceRequestStatutId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<long> IMSCardId { get; set; }
    
        public virtual DeviceRequestStatu DeviceRequestStatu { get; set; }
        public virtual DeviceType DeviceType { get; set; }
        public virtual IMSMembership IMSMembership { get; set; }
        public virtual Member Member { get; set; }
    }
}
