//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceTypeTranslation
    {
        public int Id { get; set; }
        public int DeviceTypeId { get; set; }
        public string Locale { get; set; }
        public string Description { get; set; }
    
        public virtual DeviceType DeviceType { get; set; }
    }
}
