//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectDepositLog
    {
        public long Id { get; set; }
        public string BankId { get; set; }
        public string Currency { get; set; }
        public int SequenceNumber { get; set; }
        public string Filename { get; set; }
        public decimal Amount { get; set; }
        public Nullable<bool> FileCreated { get; set; }
        public Nullable<System.DateTime> FileCreationDate { get; set; }
        public Nullable<bool> FileShipped { get; set; }
        public Nullable<System.DateTime> FileShippedDate { get; set; }
        public string LogFilename { get; set; }
        public Nullable<int> LogFileStatus { get; set; }
        public Nullable<System.DateTime> LogFileDate { get; set; }
    }
}
