//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public long Id { get; set; }
        public long MemberId { get; set; }
        public Nullable<long> OldMembershipId { get; set; }
        public long NewMembershipId { get; set; }
        public int OrderId { get; set; }
        public int EnrollmentProcessId { get; set; }
        public string EnrollmentProcessResponse { get; set; }
        public int EnrollmentSequenceNumber { get; set; }
        public int EnrollmentStatusId { get; set; }
        public string BatchNumber { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public Nullable<long> OtherId { get; set; }
    
        public virtual EnrollmentProcess EnrollmentProcess { get; set; }
        public virtual EnrollmentStatu EnrollmentStatu { get; set; }
        public virtual IMSMembership IMSMembership { get; set; }
        public virtual IMSMembership IMSMembership1 { get; set; }
        public virtual Member Member { get; set; }
    }
}
