//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnterpriseStateTaxNumber
    {
        public int Id { get; set; }
        public int StateTaxeId { get; set; }
        public long EnterpriseId { get; set; }
        public string TaxNumber { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Enterprise Enterprise { get; set; }
        public virtual StateTax StateTax { get; set; }
    }
}
