//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLogging
    {
        public long Id { get; set; }
        public int ErrorLoggingStatusId { get; set; }
        public string Application { get; set; }
        public string Method { get; set; }
        public string Parameters { get; set; }
        public string Exception { get; set; }
        public string InnerException { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual ErrorLoggingStatu ErrorLoggingStatu { get; set; }
    }
}
