//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftCardPurchas
    {
        public long Id { get; set; }
        public long MemberId { get; set; }
        public decimal Amount { get; set; }
        public string ReceiverName { get; set; }
        public string Message { get; set; }
        public bool IsVirtual { get; set; }
        public string ReceiverEmail { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<long> PromoCodeId { get; set; }
        public Nullable<System.DateTime> EmailConfirmationDate { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual PromoCode PromoCode { get; set; }
        public virtual Member Member { get; set; }
    }
}
