//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMS_Header()
        {
            this.IMS_Detail = new HashSet<IMS_Detail>();
            this.IncentiveProgramRefunds = new HashSet<IncentiveProgramRefund>();
        }
    
        public long Id { get; set; }
        public long PortalId { get; set; }
        public long EnterpriseId { get; set; }
        public Nullable<long> MerchantId { get; set; }
        public Nullable<long> LocationId { get; set; }
        public Nullable<long> OutsideChannelId { get; set; }
        public Nullable<long> SalesRepId { get; set; }
        public Nullable<long> ContractCommissionId { get; set; }
        public Nullable<long> TerminalId { get; set; }
        public int CurrencyId { get; set; }
        public decimal OpeningAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal DueAmount { get; set; }
        public decimal ClosingAmount { get; set; }
        public int CurrentFiscalMonth { get; set; }
        public int CurrentFiscalYear { get; set; }
        public string BatchNumber { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<int> PaymentStatusId { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual ContractCommission ContractCommission { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Enterprise Enterprise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_Detail> IMS_Detail { get; set; }
        public virtual OutsideChannel OutsideChannel { get; set; }
        public virtual PaymentStatu PaymentStatu { get; set; }
        public virtual SalesRep SalesRep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncentiveProgramRefund> IncentiveProgramRefunds { get; set; }
        public virtual Location Location { get; set; }
        public virtual Merchant Merchant { get; set; }
    }
}
