//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMSCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMSCard()
        {
            this.CardPointHistories = new HashSet<CardPointHistory>();
            this.MemberPromoCodeHistories = new HashSet<MemberPromoCodeHistory>();
            this.DeviceRequests = new HashSet<DeviceRequest>();
            this.DeviceRequests1 = new HashSet<DeviceRequest>();
        }
    
        public long Id { get; set; }
        public string CardNumber { get; set; }
        public int CardTypeId { get; set; }
        public int LanguageId { get; set; }
        public string CardDesignSpecification { get; set; }
        public Nullable<long> MemberId { get; set; }
        public int CardStatusId { get; set; }
        public System.Guid ActivationNumber { get; set; }
        public string TransaxId { get; set; }
        public long EnterpriseID { get; set; }
        public long ProgramID { get; set; }
        public Nullable<int> PrefixPoints { get; set; }
        public Nullable<int> BalancePoints { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> RenewalNotificationDate { get; set; }
        public bool NoShipping { get; set; }
        public bool IsVirtual { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardPointHistory> CardPointHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberPromoCodeHistory> MemberPromoCodeHistories { get; set; }
        public virtual Program Program { get; set; }
        public virtual CardStatus CardStatus { get; set; }
        public virtual Enterprise Enterprise { get; set; }
        public virtual CardType CardType { get; set; }
        public virtual Language Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceRequest> DeviceRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceRequest> DeviceRequests1 { get; set; }
    }
}
