//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMSEnterpriseParameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMSEnterpriseParameter()
        {
            this.IMSEnterpriseParameterTerminals = new HashSet<IMSEnterpriseParameterTerminal>();
        }
    
        public long Id { get; set; }
        public long EnterpriseId { get; set; }
        public string ProviderId { get; set; }
        public string AcquirerId { get; set; }
        public string MerchantId { get; set; }
        public string TerminalId { get; set; }
        public Nullable<decimal> MaxPercentDiscountPerPromotion { get; set; }
        public Nullable<decimal> MaxPercentAmountPerPromotion { get; set; }
        public System.DateTime FiscalYearEnd { get; set; }
        public string DefaultLanguage { get; set; }
        public System.TimeSpan BatchCloseTime { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMSEnterpriseParameterTerminal> IMSEnterpriseParameterTerminals { get; set; }
    }
}
