//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMSMembership
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMSMembership()
        {
            this.Enrollments = new HashSet<Enrollment>();
            this.Enrollments1 = new HashSet<Enrollment>();
            this.MembershipTransactionDetails = new HashSet<MembershipTransactionDetail>();
            this.DeviceRequests = new HashSet<DeviceRequest>();
        }
    
        public long Id { get; set; }
        public string TransaxId { get; set; }
        public long MemberID { get; set; }
        public long ProgramID { get; set; }
        public Nullable<long> PromoCodeId { get; set; }
        public bool NoShipping { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> RenewalNotificationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollments1 { get; set; }
        public virtual Program Program { get; set; }
        public virtual PromoCode PromoCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembershipTransactionDetail> MembershipTransactionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceRequest> DeviceRequests { get; set; }
        public virtual Member Member { get; set; }
    }
}
