//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMSPointTracker
    {
        public long Id { get; set; }
        public long enterpriseId { get; set; }
        public System.DateTime dateTracker { get; set; }
        public long transactionToDay { get; set; }
        public long pointsGivenToDay { get; set; }
        public long pointsGivenToMonth { get; set; }
        public long pointsGivenToYear { get; set; }
        public long pointsGivenTotal { get; set; }
        public long pointsRedeemToDay { get; set; }
        public long pointsRedeemToMonth { get; set; }
        public long pointsRedeemToYear { get; set; }
        public long pointsRedeemTotal { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
    
        public virtual Enterprise Enterprise { get; set; }
    }
}
