//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncentiveProgramRefund
    {
        public long Id { get; set; }
        public long LocationPromoCodeId { get; set; }
        public long FinancialTransactionId { get; set; }
        public decimal BaseAmount { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal BaseRefund { get; set; }
        public decimal TaxRefund { get; set; }
        public bool OnSpotTransaction { get; set; }
        public System.DateTime TransactionDateTime { get; set; }
        public System.DateTime RefundDateTime { get; set; }
        public decimal PercentageRefund { get; set; }
        public System.DateTime CreationDate { get; set; }
        public long HeaderId { get; set; }
    
        public virtual IMS_Header IMS_Header { get; set; }
        public virtual LocationPromoCode LocationPromoCode { get; set; }
        public virtual TrxFinancialTransaction TrxFinancialTransaction { get; set; }
    }
}
