//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationBusinessHour
    {
        public long Id { get; set; }
        public long LocationId { get; set; }
        public int DayOfWeekID { get; set; }
        public System.TimeSpan OpeningHour { get; set; }
        public System.TimeSpan ClosingHour { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
