//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationPromoCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocationPromoCode()
        {
            this.IncentiveProgramRefunds = new HashSet<IncentiveProgramRefund>();
        }
    
        public long Id { get; set; }
        public long LocationId { get; set; }
        public long PromoCodeId { get; set; }
        public decimal PercentOnSpot { get; set; }
        public decimal PercentCommunity { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncentiveProgramRefund> IncentiveProgramRefunds { get; set; }
        public virtual PromoCode PromoCode { get; set; }
        public virtual Location Location { get; set; }
    }
}
