//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.ContractLocations = new HashSet<ContractLocation>();
            this.EnrollLocations = new HashSet<EnrollLocation>();
            this.IMS_Header = new HashSet<IMS_Header>();
            this.Location_Terminals = new HashSet<Location_Terminals>();
            this.LocationHolidays = new HashSet<LocationHoliday>();
            this.LocationMemberDistances = new HashSet<LocationMemberDistance>();
            this.LocationPromoCodes = new HashSet<LocationPromoCode>();
            this.LocationPromotionCalendars = new HashSet<LocationPromotionCalendar>();
            this.LocationTaxes = new HashSet<LocationTax>();
            this.MonthlyBonusPoints = new HashSet<MonthlyBonusPoint>();
            this.PromotionCalendarNotifications = new HashSet<PromotionCalendarNotification>();
            this.IMSUsers = new HashSet<IMSUser>();
            this.Promotions = new HashSet<Promotion>();
            this.LocationBusinessHours = new HashSet<LocationBusinessHour>();
            this.Subscriptions = new HashSet<Subscription>();
            this.MerchantTransactions = new HashSet<MerchantTransaction>();
        }
    
        public long Id { get; set; }
        public string TransaxId { get; set; }
        public long MerchantId { get; set; }
        public string Name { get; set; }
        public string Telephone { get; set; }
        public long AddressId { get; set; }
        public Nullable<long> BankingInfoId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int TimeZoneId { get; set; }
        public Nullable<bool> ApplyTaxes { get; set; }
        public Nullable<bool> EnableTips { get; set; }
        public Nullable<bool> PayWithPoints { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractLocation> ContractLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrollLocation> EnrollLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_Header> IMS_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Location_Terminals> Location_Terminals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationHoliday> LocationHolidays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationMemberDistance> LocationMemberDistances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationPromoCode> LocationPromoCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationPromotionCalendar> LocationPromotionCalendars { get; set; }
        public virtual TimeZone TimeZone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationTax> LocationTaxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonthlyBonusPoint> MonthlyBonusPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionCalendarNotification> PromotionCalendarNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMSUser> IMSUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promotion> Promotions { get; set; }
        public virtual Merchant Merchant { get; set; }
        public virtual BankingInfo BankingInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationBusinessHour> LocationBusinessHours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MerchantTransaction> MerchantTransactions { get; set; }
    }
}
