//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipTransactionDetail
    {
        public long Id { get; set; }
        public long HeaderId { get; set; }
        public int LineItemId { get; set; }
        public Nullable<long> IMSMembershipId { get; set; }
        public decimal Amount { get; set; }
        public string ApprovalNbr { get; set; }
        public string TraceNbr { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual IMSMembership IMSMembership { get; set; }
        public virtual MembershipTransactionHeader MembershipTransactionHeader { get; set; }
    }
}
