//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Merchant()
        {
            this.Contracts = new HashSet<Contract>();
            this.IMS_Header = new HashSet<IMS_Header>();
            this.Locations = new HashSet<Location>();
            this.merchant_translations = new HashSet<merchant_translations>();
            this.MerchantEvaluations = new HashSet<MerchantEvaluation>();
            this.MerchantImages = new HashSet<MerchantImage>();
            this.MerchantTags = new HashSet<MerchantTag>();
            this.Packages = new HashSet<Package>();
            this.Ratings = new HashSet<Rating>();
            this.Enterprises = new HashSet<Enterprise>();
            this.Members = new HashSet<Member>();
            this.IMSUsers = new HashSet<IMSUser>();
            this.Subscriptions = new HashSet<Subscription>();
            this.MerchantTransactions = new HashSet<MerchantTransaction>();
            this.MerchantProcessors = new HashSet<MerchantProcessor>();
        }
    
        public long Id { get; set; }
        public Nullable<int> EntityTypeId { get; set; }
        public string TransaxId { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string About { get; set; }
        public string VideoLink { get; set; }
        public string WebLink { get; set; }
        public string FacebookLink { get; set; }
        public Nullable<long> BankingInfoId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<System.Guid> LogoId { get; set; }
        public Nullable<System.Guid> MobileId { get; set; }
        public Nullable<int> PricingCategoryId { get; set; }
        public Nullable<bool> TaxableProduct { get; set; }
        public Nullable<long> ProgramId { get; set; }
        public string Status { get; set; }
        public string LogoPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMS_Header> IMS_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Location> Locations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<merchant_translations> merchant_translations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MerchantEvaluation> MerchantEvaluations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MerchantImage> MerchantImages { get; set; }
        public virtual MerchantImage MerchantImage { get; set; }
        public virtual MerchantImage MerchantImage1 { get; set; }
        public virtual PricingCategory PricingCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MerchantTag> MerchantTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package> Packages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enterprise> Enterprises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member> Members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMSUser> IMSUsers { get; set; }
        public virtual BankingInfo BankingInfo { get; set; }
        public virtual Program Program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MerchantTransaction> MerchantTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MerchantProcessor> MerchantProcessors { get; set; }
    }
}
