//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantTransaction
    {
        public System.Guid Id { get; set; }
        public int TransactionTypeId { get; set; }
        public long MerchantId { get; set; }
        public long LocationId { get; set; }
        public decimal TransactionAmount { get; set; }
        public Nullable<decimal> AuthorizedAmount { get; set; }
        public string AuthorizationCode { get; set; }
        public string TransactionStatus { get; set; }
        public string TransactionMessage { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public long ReferenceId { get; set; }
        public Nullable<System.DateTime> TransactionStartPeriod { get; set; }
        public Nullable<System.DateTime> TransactionEndPeriod { get; set; }
        public int CurrencyId { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Location Location { get; set; }
        public virtual Merchant Merchant { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
