//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantTag
    {
        public long Id { get; set; }
        public long MerchantId { get; set; }
        public int TagId { get; set; }
    
        public virtual tag tag { get; set; }
        public virtual Merchant Merchant { get; set; }
    }
}
