//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantEvaluation
    {
        public long Id { get; set; }
        public long MemberId { get; set; }
        public long MerchantId { get; set; }
        public int EvaluationCategoryId { get; set; }
        public int Rating { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual EvaluationCategory EvaluationCategory { get; set; }
        public virtual Member Member { get; set; }
        public virtual Merchant Merchant { get; set; }
    }
}
