//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long Id { get; set; }
        public int NotificationTypeId { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool Removed { get; set; }
        public int NotificationStatusId { get; set; }
        public Nullable<int> CampaignId { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public string EmailContent { get; set; }
        public Nullable<int> ReferenceId { get; set; }
    
        public virtual NotificationStatu NotificationStatu { get; set; }
        public virtual NotificationType NotificationType { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
