//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotificationType()
        {
            this.Notifications = new HashSet<Notification>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int Frequency { get; set; }
        public int Interval { get; set; }
        public bool SendEmail { get; set; }
        public bool DisplayBanner { get; set; }
        public Nullable<int> NotificationMessageId { get; set; }
    
        public virtual NotificationMessage NotificationMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
