//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutsideChannelStyle
    {
        public long Id { get; set; }
        public long OutsideChannelId { get; set; }
        public string StyleType { get; set; }
        public string FilePath { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool FlaggedForDeletion { get; set; }
    
        public virtual OutsideChannel OutsideChannel { get; set; }
    }
}
