//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package()
        {
            this.Promotions = new HashSet<Promotion>();
        }
    
        public long Id { get; set; }
        public long EnterpriseId { get; set; }
        public long MerchantId { get; set; }
        public int PackageTypeId { get; set; }
        public Nullable<double> PackageCommission { get; set; }
        public long ContractId { get; set; }
        public string Name { get; set; }
        public double MinRebatePercent { get; set; }
        public double MinBonusPercent { get; set; }
        public int MaxPackageSales { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> StartingDate { get; set; }
        public Nullable<System.DateTime> EndingDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Enterprise Enterprise { get; set; }
        public virtual PackageType PackageType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promotion> Promotions { get; set; }
        public virtual Merchant Merchant { get; set; }
    }
}
