//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PackageType()
        {
            this.Packages = new HashSet<Package>();
            this.PackageType_translations = new HashSet<PackageType_translations>();
        }
    
        public int Id { get; set; }
        public long EnterpriseId { get; set; }
        public string Description { get; set; }
        public bool AllowRebate { get; set; }
        public bool AllowBonification { get; set; }
        public int MinDaysOnline { get; set; }
        public int MaxDaysOnline { get; set; }
        public decimal PackageFees { get; set; }
        public double PackageCommission { get; set; }
        public bool AllYear { get; set; }
        public double MinCommissionAllYear { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Enterprise Enterprise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package> Packages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageType_translations> PackageType_translations { get; set; }
    }
}
