//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionCalendarNotification
    {
        public long Id { get; set; }
        public System.DateTime TargetedDate { get; set; }
        public long LocationId { get; set; }
        public System.DateTime NotificationDate { get; set; }
        public string NotificationNewsletter { get; set; }
        public System.DateTime WarningDate { get; set; }
        public string WarningNewsletter { get; set; }
        public Nullable<System.DateTime> SelectedDate { get; set; }
        public string SelectedNewsletter { get; set; }
        public Nullable<long> SelectedPromoCalendarId { get; set; }
        public string SelectedBy { get; set; }
    
        public virtual PromotionCalendar PromotionCalendar { get; set; }
        public virtual Location Location { get; set; }
    }
}
