//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referral
    {
        public long Id { get; set; }
        public int ReferralCampaignId { get; set; }
        public long ReferredBy { get; set; }
        public string ReferredToEmail { get; set; }
        public Nullable<long> ReferredTo { get; set; }
        public bool IsProfileCompleted { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
    
        public virtual ReferralCampaign ReferralCampaign { get; set; }
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
    }
}
