//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public long Id { get; set; }
        public long MerchantId { get; set; }
        public long ProgramId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> BillingStartDate { get; set; }
        public int BillingPeriodId { get; set; }
        public Nullable<decimal> BillingAmount { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public long LocationId { get; set; }
        public long MemberId { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Merchant Merchant { get; set; }
        public virtual Program Program { get; set; }
        public virtual BillingPeriod BillingPeriod { get; set; }
        public virtual Member Member { get; set; }
    }
}
