//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateSection
    {
        public int Id { get; set; }
        public int TemplateId { get; set; }
        public int SectionId { get; set; }
        public int OrderId { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual Template Template { get; set; }
    }
}
