//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terminal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Terminal()
        {
            this.Location_Terminals = new HashSet<Location_Terminals>();
        }
    
        public long Id { get; set; }
        public string TerminalNumber { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string SerialNumber { get; set; }
        public bool IsActive { get; set; }
        public string E10001 { get; set; }
        public bool E10002 { get; set; }
        public bool E10003 { get; set; }
        public bool E10004 { get; set; }
        public bool E10005 { get; set; }
        public bool E10006 { get; set; }
        public bool E10007 { get; set; }
        public bool E10008 { get; set; }
        public bool E10009 { get; set; }
        public bool E10010 { get; set; }
        public string E10011 { get; set; }
        public bool E10012 { get; set; }
        public bool E10013 { get; set; }
        public bool E10014 { get; set; }
        public bool E10015 { get; set; }
        public bool E10016 { get; set; }
        public bool E10017 { get; set; }
        public bool E10018 { get; set; }
        public bool E10019 { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public Nullable<System.DateTime> LastSynchroDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Location_Terminals> Location_Terminals { get; set; }
    }
}
