//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Common.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrxNonFinancialTransaction
    {
        public long Id { get; set; }
        public Nullable<decimal> baseAmount { get; set; }
        public Nullable<decimal> aditionalAmount { get; set; }
        public Nullable<decimal> tip { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> approvedAmount { get; set; }
        public string cardNonFinancialId { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> pointsExpended { get; set; }
        public Nullable<int> pointsGained { get; set; }
        public Nullable<System.DateTime> systemDateTime { get; set; }
        public Nullable<System.DateTime> localDateTime { get; set; }
        public string program { get; set; }
        public string entityId { get; set; }
        public string promotion_appliedId { get; set; }
        public string vendorId { get; set; }
        public Nullable<int> inputModeId { get; set; }
        public Nullable<int> transactionTypeId { get; set; }
        public Nullable<int> voided { get; set; }
        public Nullable<int> refunded { get; set; }
        public Nullable<int> concluded { get; set; }
        public string receipt { get; set; }
        public long EnterpriseId { get; set; }
        public string transaxTerminalId { get; set; }
        public string description { get; set; }
        public Nullable<long> memberId { get; set; }
        public string orderNumber { get; set; }
        public Nullable<int> terminalId { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public string responseMessage { get; set; }
    }
}
